<a href="https://colab.research.google.com/github/Dn00z/ml-lab-01/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

train_ds = pd.read_csv("data/train.csv")
valid_ds = pd.read_csv("data/valid.csv")

l1 = 'label_1'
l2 = 'label_2'
l3 = 'label_3'
l4 = 'label_4'

features = [f'feature_{i}' for i in range(1, 257)]
labels = [l1, l2, l3, l4]

x_train = {}
x_valid = {}
y_train = {}
y_valid = {}


In [ ]:
from sklearn.preprocessing import RobustScaler

for label in labels:
    tr_ds = train_ds[train_ds[l2].notna()] if label == l2 else train_ds
    vl_ds = valid_ds[valid_ds[l2].notna()] if label == l2 else valid_ds

    scaler = RobustScaler()
    x_train[label] = pd.DataFrame(scaler.fit_transform(tr_ds.drop(labels, axis=1)), columns=features)
    y_train[label] = tr_ds[label]

    x_valid[label] = pd.DataFrame(scaler.transform(vl_ds.drop(labels, axis=1)), columns=features)
    y_valid[label] = vl_ds[label]

NameError: ignored

In [ ]:
train_ds[l3].value_counts()

label_3
1    22796
0     5724
Name: count, dtype: int64

######################################################     Label 01 [Before feature engineering]                ############################################################################################

In [ ]:
from sklearn import svm

model = svm.SVC(kernel='linear')
model.fit(x_train[l1], y_train[l1])

SVC(kernel='linear')

In [ ]:
from sklearn import metrics

y_pred = model.predict(x_valid[l1])

print(metrics.confusion_matrix(y_valid[l1], y_pred))
print(metrics.accuracy_score(y_valid[l1], y_pred))
print(metrics.precision_score(y_valid[l1], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l1], y_pred, average='weighted'))


[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.9906666666666667
0.9914608132608134
0.9906198466303276


Label 01 [Feauture Engineering]

----------------------------Using SelectKBest Univariate feature selection--------------------------------------

In [ ]:
from sklearn.feature_selection import SelectKBest, SelectPercentile, f_classif

selector = SelectKBest(f_classif, k=120)
x_train_new = selector.fit_transform(x_train[l1], y_train[l1])


In [ ]:
x_train_new.shape

(28520, 120)

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train_new, y_train[l1])

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(selector.transform(x_valid[l1]))

print(metrics.confusion_matrix(y_valid[l1], y_pred))
print(metrics.accuracy_score(y_valid[l1], y_pred))
print(metrics.precision_score(y_valid[l1], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l1], y_pred, average='weighted'))

[[12  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  9]]
0.9826666666666667
0.983401554001554
0.9826344407436685


-----------------------Using SelectPercentile feature selection--------------------------------

In [ ]:
selector = SelectPercentile()
x_train_new = selector.fit_transform(x_train[l1], y_train[l1])

In [ ]:
x_train_new.shape

(28520, 26)

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train_new, y_train[l1])

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(selector.transform(x_valid[l1]))

print(metrics.confusion_matrix(y_valid[l1], y_pred))
print(metrics.accuracy_score(y_valid[l1], y_pred))
print(metrics.precision_score(y_valid[l1], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l1], y_pred, average='weighted'))

[[10  0  0 ...  0  0  0]
 [ 0  6  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 16  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  8]]
0.824
0.8345576267328592
0.8231966284047586


------------------------------------- Using Principal component analysis -------------------------------------------------

In [ ]:
from sklearn.decomposition import PCA

selector = PCA(n_components=0.985, svd_solver='full')
x_train_new = pd.DataFrame(selector.fit_transform(x_train[l1]))


In [ ]:
x_train_new.shape

(28520, 96)

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train_new, y_train[l1])

SVC(kernel='linear')

In [ ]:
x_valid_new = pd.DataFrame(selector.transform(x_valid[l1]))
y_pred = model.predict(x_valid_new)

print(metrics.confusion_matrix(y_valid[l1], y_pred))
print(metrics.accuracy_score(y_valid[l1], y_pred))
print(metrics.precision_score(y_valid[l1], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l1], y_pred, average='weighted'))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
0.988
0.9890635068635069
0.9879733480308878


#################################################################         Label 02 [Before feature Engineering]             ############################################################################################

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train[l2], y_train[l2])

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(x_valid[l2])

print(metrics.confusion_matrix(y_valid[l2], y_pred))
print(metrics.accuracy_score(y_valid[l2], y_pred))
print(metrics.precision_score(y_valid[l2], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l2], y_pred, average='weighted'))

[[ 33   0   0   0   2   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0  67   0   2   2   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   1  41   0   2   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   9   1  64   2   1   0   0   2   0   0   0   0   0   0   0   0]
 [  0   4   2   1 103   3   0   1   0   1   0   0   0   0   0   0   0]
 [  0   4   2   0   2  67   1   1   2   2   0   0   0   0   0   0   0]
 [  0   0   1   0   2   1  42   0   0   0   0   0   0   0   0   0   0]
 [  2   1   0   0   1   0   0  40   1   0   0   0   0   0   0   0   0]
 [  0   1   0   1   0   2   0   0  44   0   0   0   0   0   0   0   0]
 [  0   2   1   3   2   1   1   0   2  52   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0   0   0  29   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  11   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  11   0   0   0]
 [  0 

------------------------------------------Feature engineering using PCA----------------------------------------------------

In [ ]:
selector = PCA(n_components=0.985, svd_solver='full')
x_train_new = pd.DataFrame(selector.fit_transform(x_train[l2]))

In [ ]:
x_train_new.shape

(28040, 96)

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train_new, y_train[l2])

SVC(kernel='linear')

In [ ]:

x_valid_new = pd.DataFrame(selector.transform(x_valid[l2]))
y_pred = model.predict(x_valid_new)

print(metrics.confusion_matrix(y_valid[l2], y_pred))
print(metrics.accuracy_score(y_valid[l2], y_pred))
print(metrics.precision_score(y_valid[l2], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l2], y_pred, average='weighted'))

[[32  1  0  0  1  0  1  0  0  1  0  0  0  0  0  0  0]
 [ 0 59  1  3  4  2  0  0  1  1  0  0  0  0  0  0  0]
 [ 1  2 39  0  2  1  0  0  0  1  0  0  0  0  0  0  0]
 [ 1  7  1 60  4  2  0  0  3  0  0  0  0  0  1  0  0]
 [ 1  6  5  6 91  1  0  2  1  2  0  0  0  0  0  0  0]
 [ 0  5  2  4  5 55  1  1  2  6  0  0  0  0  0  0  0]
 [ 0  0  1  1  3  2 39  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  1  0  1  1  0 36  1  2  0  0  0  0  0  0  0]
 [ 0  3  0  2  1  4  0  0 37  1  0  0  0  0  0  0  0]
 [ 2  5  3  6  4  1  2  1  1 40  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0 18]]
0.8002717391304348
0.8051705974586526
0.8001254370846315


#########################################################################        Label 03 [ before feature engineering] ####################################################################################

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train[l3], y_train[l3])

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(x_valid[l3])

print(metrics.confusion_matrix(y_valid[l3], y_pred))
print(metrics.accuracy_score(y_valid[l3], y_pred))
print(metrics.precision_score(y_valid[l3], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l3], y_pred, average='weighted'))

[[142   0]
 [  1 607]]
0.9986666666666667
0.9986759906759908
0.9986684571511081


---------------------------------Feature engineering using PCA----------------------------------------------

In [ ]:
selector = PCA(n_components=0.985, svd_solver='full')
x_train_new = pd.DataFrame(selector.fit_transform(x_train[l3]))

In [ ]:
x_train_new.shape

(28520, 96)

In [ ]:
model = svm.SVC(kernel='linear')
model.fit(x_train_new, y_train[l3])

SVC(kernel='linear')

In [ ]:

x_valid_new = pd.DataFrame(selector.transform(x_valid[l3]))
y_pred = model.predict(x_valid_new)

print(metrics.confusion_matrix(y_valid[l3], y_pred))
print(metrics.accuracy_score(y_valid[l3], y_pred))
print(metrics.precision_score(y_valid[l3], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l3], y_pred, average='weighted'))

[[142   0]
 [  2 606]]
0.9973333333333333
0.9973703703703705
0.99734046074738


#########################################################################        Label 04 [ before feature engineering] ####################################################################################

In [ ]:
model = svm.SVC(kernel='linear', class_weight='balanced')
model.fit(x_train[l4], y_train[l4])

SVC(class_weight='balanced', kernel='linear')

In [ ]:
y_pred = model.predict(x_valid[l4])

print(metrics.accuracy_score(y_valid[l4], y_pred))

0.9293333333333333


---------------------------------Feature engineering using PCA----------------------------------------------

In [ ]:
selector = PCA(n_components=0.985, svd_solver='full')
x_train_new = pd.DataFrame(selector.fit_transform(x_train[l4]))

In [ ]:
model = svm.SVC(kernel='linear', class_weight='balanced')
model.fit(x_train_new, y_train[l4])

SVC(class_weight='balanced', kernel='linear')

In [ ]:
x_valid_new = pd.DataFrame(selector.transform(x_valid[l4]))
y_pred = model.predict(x_valid_new)

print(metrics.confusion_matrix(y_valid[l4], y_pred))
print(metrics.accuracy_score(y_valid[l4], y_pred))
print(metrics.precision_score(y_valid[l4], y_pred, average='weighted'))
print(metrics.f1_score(y_valid[l4], y_pred, average='weighted'))

[[ 20   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0  10   1   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0  26   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   8   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  14   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0  11   0   0   0   0   0   0   0   0]
 [ 26   5  22   6   2   8 423  11   2   1   4   0  22   0]
 [  0   0   1   0   1   0   4  25   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2   0  17   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  17   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  10   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0  25   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   9]]
0.8346666666666667
0.8937042957333098
0.8478296424924299
